version: '3.7'

services:

    db:
        image: postgres:15
        container_name: database_ignite
        restart: always
        ports:
          - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite-123
            - POSTGRES_DB=rentx
        
    app:
        build: .
        container_name: rentx
        ports:
          - 3333:3333
        links:
          - db:db
        depends_on:
            - db
        volumes:
            - .:/usr/app

volumes:
    pgdata: